Repository ROCm/hipSPARSELt, pull requests merged in 2025-06, with the labels that each got.

#245 Cherry-pick to release/rocm-rel-6.4: First phase of the hipSPARSELt docs refresh
  .wordlist.txt
  docs/conceptual/mi300-features.rst
  docs/conceptual/storage-format.rst
  docs/conf.py
  docs/data/prune-workflow.drawio
  docs/data/prune-workflow.svg
  docs/how-to/device-stream-management.rst
  docs/how-to/porting.rst
  docs/index.rst
  docs/install/install-hipsparselt.rst
  docs/install/quick-start-install.rst
  docs/reference/supported-functions.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/install/linux.rst
  docs/tutorials/quick-start/linux.rst
  docs/what-is-hipsparselt.rst
Labels: documentation, ci:docs-only

#247 Remove unused internal helper functions.
  library/src/hcc_detail/hipsparselt.cpp
  library/src/hcc_detail/rocsparselt/src/handle.cpp
  library/src/hcc_detail/rocsparselt/src/include/rocsparselt_spmm_utils.hpp
  library/src/hcc_detail/rocsparselt/src/include/tensile_host.hpp
  library/src/hcc_detail/rocsparselt/src/include/utility.hpp
  library/src/hcc_detail/rocsparselt/src/rocsparselt_auxiliary.cpp
  library/src/hcc_detail/rocsparselt/src/spmm/rocsparselt_compress.cpp
  library/src/hcc_detail/rocsparselt/src/spmm/rocsparselt_prune.cpp
  library/src/hcc_detail/rocsparselt/src/utility.cpp
Labels: ci:codecoverage, gfx950

#249 Update tensilelite_tag
  tensilelite_tag.txt
Labels: gfx950
